---
title: "180823-1023-mdt_interview-flashcards.Rmd"
---

# Status:

- _180822-1030-mdt_interview-flashcards.Rmd_
  - Began/completed flashcard fronts for AFI chapters 6-9.


# Plans:

- Interview flashcards:
  - AFI flashcard fronts:
    - Chapter 10.
    - Chapter 11. The first four sections will be fairly short, and all subsequent sections will be pretty long.
  - Setup flashcard fronts and backs for recently-studied algorithms and data structures outside of AFI.
  - Setup combinatorics flashcards, fronts and backs, for recently-studied topics.
  - Fill in fronts of AFI flashcards that I've recently answered. Python only, for now.
  - Begin working through answers for remaining AFI flashcard. Python only.
- Spend 2--3 hours this evening on personal projects.


# Log:

##### 0645-ish: Personal errands.

##### 1038: Start; status/thoughts/plans.

##### 1108: Setup/start AFI chapter 10 flashcards.

##### 1447: Completed chapter 10 fronts. Break.

##### 1504: Setup/start AFI chapter 11 fronts.

##### 2015: Completed chapter 11 fronts. Stopping.
