---
title: "180920-1432-mdt_algorithms-and-math.Rmd"
---

# Status:

- Two days ago on 180918:
  - CCAC (Calculus: Concepts & Contexts): calculus diagnostic problems 00.A 01 and 02. Mostly I was setting up for upcoming work.
- Yesterday, _180919-0845-mdt_algorithms_:
  - Flashcard system:
    - Added new notes field `ExtraTags`. I'm using this to mark notes as "Done", or coding notes as "Done-Python" and so on.
  - AFI problems:
    - 01.02: Search a sorted array for \(k\)
    - 01.08: Anagrams
    - 01.09: Search for a pair which sums to \(S\)
    - 01.16: Search BST for a key
    - 01.17: Search BST for \(x > k\)
    - 02.01 Good sorting algorithms
    - 02.10: Merging sorted arrays
  - CCAC problems:
    - RoA (Review of Algebra): created section for upcoming work.

I'm going to need to switch back to personal projects soon, and I also want to work some more on data-science reviews before I start the next data-science course.

Before I do that, though, I want to get a better feel for how quickly I can work on each topic. So I'll be taking more detailed notes that include some info about how long each problem takes.


# Plans:

- Commit some work on data-science flashcards.
- Start with RoA laws/theorems flashcards; don't worry about timing.
- Then typeset RoA problem flashcards, tracking time spent per flashcard. Don't typeset solutions yet.
- Solve each problem on paper, tracking time spent per problem. Don't typeset solutions yet.
- Once all solutions written, start typesetting each solution, tracking time spent per solution.

I may not have much time today, as I have some personal things to attend to.

- If I have time, switch to practicing flashcards.
- If I still have time, plan next steps.


# Log:

##### 1432: Start; status/thoughts/plans.

##### 1516: Committing data-science flashcards.

##### 1537: RoA laws/theorems flashcards.

##### 1648: Done with RoA laws/theorems flashcards. Break.

##### 1706: Resume: RoA problem flashcards, tracking time.

```{python }
59-6
116/53
60*53/116
```
53 minutes for 116 problems. 2.19 problems per minute, 27.4 seconds per problem.


##### 1759: Done typesetting 116 RoA problem flashcards, sans solutions. Checking work.

```{python }
116/21
60*21/116
```
21 minutes for 116 problems. 5.52 problems per minute, 10.9 seconds per problem.


##### 1820: Done checking 116 RoA sans solutions. Committing work.

```{python }
116/25
60*25/116
```
25 minutes for 116 problems. 4.64 problems per minute, 12.9 seconds per problem.


##### 1845: Done committing. Break.

##### 1851: Resume. Typeset RoA solutions.

```{python }
116/37
60*37/116
```
37 minutes for 116 problems. 3.14 problems per minute, 19.1 seconds per problem.


##### 1928: Done typesetting RoA solutions. Checking.

```{python }
42-28
116/14
60*14/116
```
14 minutes for 116 problems. 8.29 problems per minute, 7.24 seconds per problem.


##### 1942: Done checking RoA solutions. Committing.

```{python }
116/18
60*18/116
```
18 minutes for 116 problems. 6.44 problems per minute, 9.31 seconds per problem.


##### 2000: Done committing RoA solutions. Computing edit rates.

```{python }
53+21+25+37+14+18
divmod(168, 60)
116/168
168/116
```

Totals:
- 2h48m (168m) for 116 problems.
- 0.69 problems per minute.
- 1.44 minutes per problem.


##### 2015: Stopping.
