---
title: "180919-0845-mdt_algorithms.Rmd"
---

Related private notes: _180919-0845-mdt_.

# Status:

I've been working on personal projects for the last week.

Today I'm switching to studies, focusing on algorithms.
- Last work on studies was in _180906-1052-mdt_flashcards-and-datascience_, where I focused on data science.


# Plan:

- _update_yaml_notes.py_:
  - Revise, adding new notes field _ExtraTags_. The idea is to tag some notes as "Done", or "Done-Python", and so on.
- Algorithm flashcards:
  - Tag completed Python flashcards with "Done-Python". This should make it easier to keep track completed work as I transfer from notes to flashcards.
  - Transfer work from notes to flashcards.
  - Study completed Python flashcards.


# Notes:

- I need to do a detailed study of heap sort and heap properties.

# Log:

##### 0845: Start; status/thoughts/plans.

##### 0926: Revised _update_yaml_notes.py_. Now tagging done notes.

Thoughts:
- I need to test the code I'm practicing.
- The BST's delete-node code is so hairy that the AVL tree's rebalancing rotation might actually simplify things.
- I want to avoid copy-paste repetition.
  - Import implementations from module `irrealis` in _/mnt/Work/Repos/irrealis/flashcards/_.
    - Worry later about better module name.
  - Do practice work from same subdir. Include "`import`" commands in flashcard questions.

- Avoid tautological tests.
- Periodically reduce test mass.
  - Consider discarding tests that haven't failed in a long time.


  ##### 1818: Committed bunch of flashcard answers/notes; stopping.
