---
title: "180925-1314-mdt_personal-and-data-science.Rmd"
---

# Status:

- Yesterday, _180924-1412-mdt_algebra-drills_data-science_personal_:
  - Spent most of day finishing algebra review and drills. Also did some calculus review and drills, which I'll be working on later as well.

# Thoughts:

- Some personal projects need attention, and I'm shifting them upward in my priorities. Will try to address them for first half of each day, before shifting to math, data science, or algorithms.
- I need to spend more time brainstorming when I'm problem-solving.


# Plans:

- I have approximately 4-1/2 hours available today.
- Will spend 2-1/2 hours on personal projects.
- Will then shift to data science for remainder of day.
  - Picking up at Coursera's _Statistical Inference_ course, sixth of the _Data Science_ track by Johns Hopkins University.
  - Just joined session starting 24 September, ending 29 October.


# Log:

##### 1314: Start; status/thoughts/plans.

##### 1706: Switching to data science.

## Week-1:
### Module 1: Introduction
#### Video: Introductory video

- **Definition: Statistical Inference:** The process of generating conclusions about a population from a noisy sample.
  - Example: predict who will win an election given a sample of likely voters today.
    - Noise:
      - Some might not vote.
      - Some might change minds.
      - People may be deliberately misleading.
  - Example: weather prediction given historical data.
  - Example: use fMRI data to associate a task with activity in a region of the brain.
- Above examples:
  - Very different aspects of statistical inference.
  - Different ways of thinking about and modeling randomness.

- Course will focus on frequentist paradigm.

- Four quizzes.
- One project.


#### Reading: Welcome to Statistical Inference

- Foci:
  - Intro to key ideas: working with data scientifically to produce new, reproducible insights.
  - Intro tools to execute data-analytic strategy:
    - Raw data
    - Completed report
    - Interactive graphics
    - **Question: what data-analytic strategy?**
  - Hand-on practice to learn techniques.

#### Reading: Some introductory comments
#### Reading: Pre-Course Survey
#### Reading: Syllabus
#### Reading: Course Book: Statistical Inference for Data Science
#### Reading: Data Science Specialization Community Site
#### Reading: Homework Problems

#### Reading from textbook.

- https://leanpub.com/LittleInferenceBook/read#leanpub-auto-about-this-book
- _Knowledge and parsimony:_ using simplest reasonable models to explain complex phenomena.



##### 1812: Done with module one. One to module two.
##### 1818: Back up; review related module-1 mtl in course text.
##### 1850: Pausing, probably stopping for night.

### Module 2: Probability

- Eventual goal: use _probability models_ to connect data to a population.
- Requisite goal: understand basic probability calculus.

#### Reading: Probability
#### Video: 02 01 Introduction to probability
#### Video: 02 02 Probability mass functions
#### Video: 02 03 Probability density functions

### Module 3: Conditional Probability
#### Reading: Conditional probability
#### Video: 03 01 Conditional Probability
#### Video: 03 02 Bayes' rule
#### Video: 03 03 Independence

### Module 4: Expected Values
#### Reading: Expected values
#### Video: 04 01 Expected values
#### Video: 04 02 Expected values, simple examples
#### Video: 04 03 Expected values for PDFs

### Practical R Exercises in swirl
#### Reading: Practical R Exercises in swirl 1
#### Practice Programming Assignment: swirl Lesson 1: Introduction
#### Practice Programming Assignment: swirl Lesson 2: Probability1
#### Practice Programming Assignment: swirl Lesson 3: Probability2
#### Practice Programming Assignment: swirl Lesson 4: ConditionalProbability
#### Practice Programming Assignment: swirl Lesson 5: Expectations
#
### Week 1 Quiz
